workflows:
  ios-simulator:
    name: iOS Simulator Build
    working_directory: EV-APP/flutter-app/ev
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get
      - name: Build iOS Simulator App
        script: |
          flutter build ios --simulator --debug
    artifacts:
      - EV-APP/flutter-app/ev/build/ios/iphonesimulator/*.app
