// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByvoLcl2xPT1d-NN0tmk4K6R05KM2df0A',
    appId: '1:40038334977:web:cc2e615924153a8283b600',
    messagingSenderId: '40038334977',
    projectId: 'ev-app-4b0f9',
    authDomain: 'ev-app-4b0f9.firebaseapp.com',
    storageBucket: 'ev-app-4b0f9.firebasestorage.app',
    measurementId: 'G-EZ82E0K4YG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByvoLcl2xPT1d-NN0tmk4K6R05KM2df0A',
    appId: '1:40038334977:android:d2fb24de2521074a83b600',
    messagingSenderId: '40038334977',
    projectId: 'ev-app-4b0f9',
    storageBucket: 'ev-app-4b0f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByvoLcl2xPT1d-NN0tmk4K6R05KM2df0A',
    appId: '1:40038334977:ios:cc2e615924153a8283b600',
    messagingSenderId: '40038334977',
    projectId: 'ev-app-4b0f9',
    storageBucket: 'ev-app-4b0f9.firebasestorage.app',
    iosBundleId: 'com.example.ev',
  );
}
